### ISSUE TITLE
検索結果の表示内容を変更

### ISSUE THREAD

**Issue by showwin** [showwin/QIDB#113]
現状
* 指標番号
* 指標群
* 名称
* 意義

の4つの情報が表示されているが、
これを
* 指標番号
* 指標群
* 名称
* 分母 (定義の要約:分母)
* 分子 (定義の要約:分子)

の5つに変更。

**変更箇所**
<img width="1242" alt="screen_shot_2016-01-28_at_08_15_30" src="https://cloud.githubusercontent.com/assets/1732016/12631897/7e41778e-c597-11e5-9e09-7fbedaf40898.png">

<hr>

上記対応に加えて、関連する部分のテストコードも追加。
[この辺り](https://github.com/showwin/QIDB/blob/master/spec/features/home_spec.rb#L17) に `指標群` `名称` `分母` `分子` の項目を追加すると良さそう。

**Comment by showwin** [comment]
@hayayu11 @okadasato 
こちら、比較的簡単なタスクになっているので、スキル引継ぎの観点からITチームに作業を依頼したいと思っています。
実際に手を動かしての作業は、岡田さんにお願いをしたいと思っていますが、可能でしょうか。
2月12日(金) までに作業が終わるように進めて頂ければと思います。

不明点や疑問点はここに書いて頂ければ全て答えますので、お気軽にどうぞ。

@okadasato 
取り急ぎ、引き受けて頂けるかどうかのお返事だけお願い致します。

**Comment by showwin** [comment]
**2月12日まで** と書いていますが、もしそこまでに全てが完了していなければ、残りの作業はぼくが引き受けますので、とりあえずやってみるか！というような軽い気持ちで取り組んでいただければと思います。(試験の時期だと思いますので…)

**Comment by okadasato** [comment]
返信遅くなってしまいすみません。
試験が終了したため、作業に取り掛かってみようと思います。
分からないことがあれば質問させていただきますので、宜しくお願いします。

岡田


2016年1月28日木曜日、ITO Shogo<notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:

**Comment by showwin** [comment]
@okadasato ありがとうございます :+1: 
お気軽に質問くださいませ〜

**Comment by okadasato** [comment]
作業をしてみましたが、コメントにも書いた通り正しいのかわからないので、
確認よろしくお願いします。
間違っている場合、ご指南も宜しくお願いします。

**Comment by showwin** [comment]
@okadasato 
すみません、ぼくがしっかりとお伝えしなかったのですが…
[以前にプルリクエスト](https://github.com/showwin/QIDB/pull/75)を上げて頂いたように、変更分はすべてプルリクエストの形で上げて頂いて、そこでコードレビューをして問題がなければ master ブランチに merge するという方法で開発を進めたいと思っています。

先ほど master ブランチにコミットして頂いた分は revert しましたので、同じ内容でプルリクエストを上げて頂けますでしょうか。

**Comment by showwin** [comment]
@okadasato 
## エディタについて
>僕の想像では、showwin/QIDB内のapp/.../select.html.erbが変更したこのコードに差しかわると思っていたのですが、そうなっていないため、この作業が正しいのかどうかがいまいちわかっていません。

そうですね、誤った位置にファイルができてしまっていました。
どのようにファイルを編集したのかわかりませんが、もし今使っているエディタが使いにくいようでしたら、[Atom](https://atom.io/) を使うことをおすすめします。

## 開発環境について
>この作業が正しいのかどうかがいまいちわかっていません。

commit を push する前に、手元で正常に動作するか確認すると良いです。
Docker を使ってすぐに開発環境が整えられるように整備してあります。
インストール手順は [公式ページのWIndows版](https://docs.docker.com/engine/installation/windows/) を見るのが良いかと思います。`Docker windows` でググると日本語の情報もそこそこあると思います。
docker machine を作成した後の開発手順は [こちら](https://github.com/showwin/QIDB/pull/103) に説明が書いてあるので、参考にしてください。
(多分どこかで詰まると思うので、わからなかった部分はまた質問してください)

## テストコードについて
`(root_dir)/spec/*` にはテストコードがおいてあります。
テストとは、アプリケーションが想定する動きをしているかどうかをプログラムによって確かめるものです。ある機能を追加した時に、別の機能が壊れていないことを確かめることができるため、アプリケーションの品質を保つために非常に重要です。
今回は RSpec というテストのライブラリを用いて書いていて、岡田さんに開発してもらう部分に該当するテストコードは [この部分](https://github.com/showwin/QIDB/blob/master/spec/features/home_spec.rb#L17) になります。
テスト用に作成するダミーデータは [このファイル](https://github.com/showwin/QIDB/blob/master/spec/support/create_definition.rb) を使っているので、
```ruby
expect(page).to have_content('指標番号: 64') # ←すでに書いてある
expect(page).to have_content('指標群: 呼吸器系')
expect(page).to have_content('名称: 縦隔生検を実施した症例において、手技後に治療を要する気胸や血胸が生じた症例の割合')
expect(page).to have_content('分母: 18歳以上で、経胸壁的肺/縦隔生検を受けた症例')
expect(page).to have_content('分子: 分母のうち、胸腔ドレナージを受けた症例')
```
のように書き足してください。

GitHubにプルリクエストを送ると、CircleCI が自動的に動き出して、push したアプリケーションコードに対して、テストコードを実行してくれるように設定してあります。
例えば、ひとつ前のプルリクエストの時のCircleCIの結果は [ここ](https://circleci.com/gh/showwin/QIDB/56#tests) で見ることができ、 `Parallel RSpec` の項を見ると35個のテストケースがすべてパスしていることが確認できると思います。

## 変更箇所について
変更の仕方は問題無いですが、変更すべきファイルが違っています。
トップページの検索結果部分を変更してもらいたいので、`(root_dir)/app/views/home/index.html.erb`を編集してください。
[先ほどの修正](https://github.com/showwin/QIDB/commit/4ce8f305c10270e4f4b19495943b33ee9f7663df#diff-c1727d7b8410fd8220d5b4997d6d940aR48) で書いてくれているように、分母と分子は
```
<%= d.def_summary['denom'] %>
<%= d.def_summary['numer'] %>
```
で参照できるので、ここは問題ないと思います。
