### ISSUE TITLE
IEの定義書作成ボタンの有効化

### ISSUE THREAD

**Issue by tomiit** [showwin/QIDB#116]
現在IEで定義書作成ボタンが機能していないので、有効化させる。
原因はおそらくAjaxと思われると教えていただいたので、開発環境が整い次第作業します。

**Comment by showwin** [comment]
Issue の起票ありがとうございます！
「IE Ajax 動かない」とググるとたくさん情報が出てきますので、適当に試していただければと思います :bow:

**Comment by tomiit** [comment]
了解しました！
早川さんが帰ってきてissueにあげたほうがいいよと言われたので今更ながらあげました。
僕のwindowsでdocker-composeを使おうとするとエラーがでて、なかなかそのエラーをクリアできないので作業にかかれない状況です。
色々試してみて早く作業できるようにします。

**Comment by showwin** [comment]
@tomiit Docker の開発環境構築の Issue #118 を立てましたので、そちらで具体的なエラーメッセージなどを教えて頂けますでしょうか。

**Comment by tomiit** [comment]
具体的には、編集のときのみ作成ボタンが押せないようです。その他新規作成や削除についてはきちんと動いていました。

**Comment by tomiit** [comment]
重複しています、上書きしますか？というメッセージがうまくでないのか、保存された情報を更新できないのかのどちらかだと考えたのですが、前者を疑って新規作成ですでにある番号を登録しようとしたところ、同様に作成ボタンが機能しませんでしたので、そこだと思います。

**Comment by showwin** [comment]
動かない部分は、例えば [ここ](https://github.com/showwin/QIDB/blob/master/app/views/definitions/_edit_form.html.erb#L1) のように form に `remote: true` のオプションが付いている部分です。

`remote: true` にすることで、Ajax を使用してサーバーとデータのやりとりをするのですが、IEではその動きをサポートしていないため、対策が必要だという認識です。

**Comment by showwin** [comment]
>重複しています、上書きしますか？というメッセージがうまくでないのか、保存された情報を更新できないのかのどちらかだと考えたのですが、前者を疑って新規作成ですでにある番号を登録しようとしたところ、同様に作成ボタンが機能しませんでしたので、そこだと思います。

`remote: true` でレポジトリ内を検索するとわかりますが、2箇所該当します。
検索結果: https://github.com/showwin/QIDB/search?utf8=%E2%9C%93&q=remote%3A+true

さすがですね、指摘して頂いた部分のみ Ajax が使用されているようです。

**Comment by tomiit** [comment]
なるほど、remote: trueがAjaxが使われている部分なんですね！
GithubでAjax調べてみても何もなかったんでどこのことなのかと考えていました。
いろいろ試してみます。

**Comment by tomiit** [comment]
@showwin 
Ajaxについて、なぜAjaxを使っているのかと、どこのアクションにAjaxを使っているのかを教えていただけないでしょうか？

**Comment by showwin** [comment]
>どこのアクションにAjaxを使っているのかを教えていただけないでしょうか？

```
<%= form_tag(definitions_path, multipart: true, remote: true) do %>
```
であれば submit した時に `POST definitions_path` にリクエストが飛ぶので、
<img width="759" alt="screen_shot_2016-02-26_at_16_44_58" src="https://cloud.githubusercontent.com/assets/1732016/13346295/8e4254c8-dca8-11e5-859d-a1f0d94fa409.png">

DefinitionsController の create メソッド([ここ](https://github.com/showwin/QIDB/blob/master/app/controllers/definitions_controller.rb#L25))が呼ばれることがわかります。ここでは、コメントにも書いてあるとおり、必須項目の入力漏れがないかどうかや、上書き保存をすることになるかどうかを確かめています。

必須項目の入力漏れがあった場合には
<img width="497" alt="screen shot 2016-02-26 at 16 49 45" src="https://cloud.githubusercontent.com/assets/1732016/13346346/fccf6c6e-dca8-11e5-8dc1-4c164023c7f7.png">
のようにエラーメッセージを出す必要がありますが、この時に Ajax を使用しないと、フォームに入力されたデータをレンダリングする必要があり対応が面倒です。
実施にどの辺りが面倒で大変なのかは、ここで Ajax を使わないで実装しようとすると分かるかと思いますので、興味があれば試してみてください。。
