### ISSUE TITLE
Windows での Docker 開発環境構築

### ISSUE THREAD

**Issue by showwin** [showwin/QIDB#118]
Windows 環境での Docker の使用に関して知見がないので、ここで議論して開発環境構築の方法を整理する。

最下部に環境構築方法をまとめました。
以下、そのコピー
### 概要
Windows で VirtualBox 上に CentOS の環境を作成し、そのうえで Docker を動かす。

### 手順
[VirtualBox (Windows) 上に CentOS 7 をインストールする](http://qiita.com/100/items/80a899fbaeb1e82b3f67) を通りに設定を行う。
途中 `Guest Additionsの設定` のところで、 
```
Building the main Guest Additions module [失敗]
```
とエラーがでるが、それを無視して設定を続ける。
CentOS の環境ができたら、あとは [Docker の公式ページ](https://docs.docker.com/engine/installation/windows/) の通りに行えば良い。
QIDBでの使い方は [こちら](https://github.com/showwin/QIDB/pull/103) にまとまっているので、これを参考にする。

**Comment by hayayu11** [comment]
MacやWindows上では、一度(軽量な)LinuxをホストOSとして立ち上げてからDockerを使う。ホストOSを作成、管理するシステムとしては、Virtual BoxやBoot2Dockerやdocker-machineが存在する。VBは最初の仮想化OSを作成するのに必要である。

Boot2Dockerについて(01/16/2015公開)
http://pocketstudio.jp/log3/2015/01/16/boot2docker_introduction/

Hyper-V + Windowsを用いた環境構築(08/20/2015公開)
http://dev.classmethod.jp/server-side/docker_on_hyper-v/

**Comment by hayayu11** [comment]
議論とはこのような感じでまとめていくということでよろしいでしょうか。

**Comment by showwin** [comment]
曖昧な表現をしてしまってすみません、今環境構築で詰まっている部分をすべて洗い出して、それを解決して、Windows ではこのような手順でやれば環境構築できますよ！
って流れをここにまとめたかったです。

ので、とりあえず出ているエラーメッセージを書いていただければと思います。
(このような時には、それまでにどんなコマンドを打ったのかの情報もあると良いです)

**Comment by tomiit** [comment]
僕は、Windowsにdocker一式をインストールして行おうとしていたのですが、Windowsではdockerやdocker-machineはうまくいくのですが、docker-composeのみが、「Microsoft.VC90.crt.manifest could not be extracted!」といったメッセージが出ます。ネットで解決策になりそうな記事を見つけて実際にそのファイルを作成してみたのですが、うまくいきませんでした。
先ほど早川さんとも相談していたのですが、上にも書いてますよう、1度Linuxを立ち上げてそこにdockerを入れる形でやってみようと思っています。

**Comment by tomiit** [comment]
Virtualbox上にCentosを立ち上げてDockerを使おうとしているのですが、
http://qiita.com/100/items/80a899fbaeb1e82b3f67
このサイトの順に設定を行ったところ、Guest Additionsの設定のところで、
Building the main Guest Additions module [失敗]
と出て、うまくいきません。
少し古いですが、
http://little-braver.com/536/
このサイトを参考にしてみましたが、解決できませんでした。
ログを確認したのですがよくわからず、添付いたしますので見ていただきたいです。
よろしくお願いします。

2016年2月10日 19:26 ITO Shogo <notifications@github.com>:

**Comment by tomiit** [comment]
先ほどの設定のエラーを無視してGitとDockeをインストールしたところ、docker-composeでコンテナを建てることに成功し、Web上で閲覧することができました。

Firefoxで閲覧したのですが、検索ボタンを押すとエラーが起きて、また、新規作成の作成ボタンも押せませんでした。
これはFirefoxだからでしょうか？

2016年2月12日 14:35 富井択音 <tommy19960417@gmail.com>:

**Comment by showwin** [comment]
>先ほどの設定のエラーを無視してGitとDockeをインストールしたところ、docker-composeでコンテナを建てることに成功し、Web上で閲覧することができました。

それはよかったです！

>Firefoxで閲覧したのですが、検索ボタンを押すとエラーが起きて、また、新規作成の作成ボタンも押せませんでした。
すみません、具体的なエラーメッセージがわからないのでなんとも言えないです。
画面のスクリーンショットを貼っていただくか、docker-compose を起動しているターミナルに Rails のログが出ていると思いますので、そちらを貼って頂けますでしょうか。

**Comment by showwin** [comment]
@tomiit エラーが出てしまっている件に関しては別途 Issue を立てて頂けると助かります。

**Comment by showwin** [comment]
## Windows 環境での Docker 環境構築方法
### 概要
Windows で VirtualBox 上に CentOS の環境を作成し、そのうえで Docker を動かす。

### 手順
[VirtualBox (Windows) 上に CentOS 7 をインストールする](http://qiita.com/100/items/80a899fbaeb1e82b3f67) を通りに設定を行う。
途中 `Guest Additionsの設定` のところで、 
```
Building the main Guest Additions module [失敗]
```
とエラーがでるが、それを無視して設定を続ける。
CentOS の環境ができたら、あとは [Docker の公式ページ](https://docs.docker.com/engine/installation/windows/) の通りに行えば良い。
QIDBでの使い方は [こちら](https://github.com/showwin/QIDB/pull/103) にまとまっているので、これを参考にする。

**Comment by showwin** [comment]
環境構築ができたようなので close します。
