### ISSUE TITLE
proxy の設定における環境変数の使用

### ISSUE THREAD

**Issue by hayayu11** [showwin/QIDB#130]
ソースが公開されてもいいように、Dockerfile 又は docker-compose.yml 内で環境変数などを使いプロキシを指定する。

http://kokonotsu.net/log/%5Brails%5D%20github%E3%81%AB%E4%B8%8A%E3%81%92%E3%81%9F%E3%81%8F%E3%81%AA%E3%81%84%E3%83%91%E3%82%B9%E3%83%AF%E3%83%BC%E3%83%89%E7%AD%89%E3%81%AE%E7%AE%A1%E7%90%86%E6%96%B9%E6%B3%95/

**Comment by showwin** [comment]
ごめんなさい、 `ソースが公開されてもいいように` と `Dockerfile 又は docker-compose.yml 内で環境変数などを使いプロキシを指定する。` の関連性がわからなかったのですが、どういった意図でしょうか？

**Comment by hayayu11** [comment]
研究室内の仮想サーバー内で、dockerfileからqidbコンテナを立てる際に、コンテナ内でプロキシが設定されてないと、yum などのコマンドが使えませんでした。なので、一旦 dockerfile 内で ENV で指定するとコンテナが完成しました。内部で使うプロキシを公開してよいものか、外向けなのか内向けなのか判断しかねたので、環境変数を使うのが安全かと思い、issue に書きました。

**Comment by showwin** [comment]
なるほどです、ご説明ありがとうございます。
Dockerfile に Proxy の設定を書いてしまうと、その環境に依存したコンテナになってしまうため、別の方法を取るほうが望ましいように思います。

例えば、[HTTPプロキシ環境におけるdocker build](http://qiita.com/speg03/items/4b8573686e7bbf218b61) では build する時に引き数を渡してプロキシの設定を埋め込んでいます。
研究室で開発を行う場合には、このような方法で build を行うのはいかがでしょうか。

**Comment by hayayu11** [comment]
僕も dockerfile 内で サーバにENV['HTTP_PROXY'] が設定されていれば参照し、なければ無というようにするか、一手間引数を渡し docker build だけ先に行うか迷ったんですが、後者で十分ですね。 close します。
