### ISSUE TITLE
指標毎・番号毎の検索機能追加

### ISSUE THREAD

**Issue by hayayu11** [showwin/QIDB#135]
- QIPや日病の指標毎にキーワード検索出来るようにする。例えば、指標毎にプルダウンメニューを作り、キーワード検索にいちいち"QIP hogehoge"と書く必要のないようにする。
- 指標番号を直接指定して該当指標ページに直接リンク出来るようにする。

**Comment by showwin** [comment]
@hayayu11 

>指標番号を直接指定して該当指標ページに直接リンク出来るようにする。

に関して、理解が間違っていたら申し訳ないですが、
https://github.com/showwin/QIDB/blob/master/doc/README.md#43-qi定義書の閲覧-1
にあるように `/definitions/qip/2021` で指標のページにアクセスするという話ではなかったでしょうか？ 
もしそうであれば、すでに実装されているかと思いました。

>QIPや日病の指標毎にキーワード検索出来るようにする。例えば、指標毎にプルダウンメニューを作り、キーワード検索にいちいち"QIP hogehoge"と書く必要のないようにする。

個人的にはプルダウンから `QIP` を選択して、その後に検索フォームで `hogehoge` と入力するよりも、検索フォームに `QIP hogehoge` と入力するほうが短時間で入力ができるかと思うのですが、これはどういった設計意図でしたでしょうか。

**Comment by hayayu11** [comment]
@showwin
- 私もURLで直接指定出来ると一応伝えたのですが、UIとしての分かりやすさから実装の要請がありました。もう一度本当に必要か確認しても良いかもしれません。

- 検索フォームについても一応伝えたのですが、個人の感覚次第な話かと思います。これももう一度確認すべきと思います。

**Comment by showwin** [comment]
>私もURLで直接指定出来ると一応伝えたのですが、UIとしての分かりやすさから実装の要請がありました。もう一度本当に必要か確認しても良いかもしれません。

なるほど、直接URLを自分で記述するということではなくて、トップページに指標番号専用の検索フォームを設けるというお話だったわけですね。理解しました。

早川さんもお考えのように http://www.amazon.co.jp/ のようなフォーム左側にカテゴリ (QIDBの場合はプロジェクト) を選択するプルダウンのフォームを設けるのが良いでしょうか。
そうすればこの Issue の要件2つが同時に満たせるのかなと思いました。(指標番号で検索した場合に直接リンクではないですが)

一般的な話ですが、機能追加を繰り返すうちに画面上の操作/デザインが複雑化して、気付くとゴチャゴチャになっていたという話が良くあります。(開発側の人間は普段から自分たちのサイトを使っているので、複雑になっていることに気づきません)
私自身もデザインは得意ではないので人に言える立場ではありませんが、できるだけシンプルを保つ方向でUI設計をした方が良いのではないかと思います。

**Comment by hayayu11** [comment]
@showwin 
恐らく、一般の人の"慣れ"という観点では、URLリクエストの処理よりも検索バーに入力する方が好まれるのかもしれません。私も丁度 amazon のようなものを考えていましたので、もう一度先生に念を押した後に取りかかろうと思います。

**Comment by hayayu11** [comment]
とりかかることに決定。
