### ISSUE TITLE
デプロイの方法

### ISSUE THREAD

**Issue by hayayu11** [showwin/QIDB#146]
@showwin 本番環境でのデプロイは仕様書の開発手順に示されていると思いますが、リモートの release ブランチを最新の状態にすれば自動的にその内容が反映されるということでしょうか？

**Comment by showwin** [comment]
です！
デプロイ成功したかどうかは https://circleci.com/gh/showwin/QIDB を見てもらえば分かると思います〜！

**Comment by hayayu11** [comment]
現在の release ブランチは最新のmasterと同じコードだと思います。上記のURLを見ると常にローディングされている状態です。自動的なデプロイはこれほど時間がかかるものなのでしょうか？

**Comment by showwin** [comment]
https://circleci.com/gh/showwin/QIDB/134 `release` ブランチのCIが Failed してますね…
エラーメッセージ見る感じSSHキーの問題な気がします… (特に何も変えてない気がするけど、なんでFailしてるんだろな…)

**Comment by showwin** [comment]
ちょっと今週末時間あったら見ておきます…
でスケジュール的にOKですかね！？

**Comment by hayayu11** [comment]
お忙しいところありがとうございます。大丈夫です。

**Comment by showwin** [comment]
デプロイできない問題修正しました〜
https://circleci.com/gh/showwin/QIDB/136

(ぼくがSSH鍵の登録を削除してしまっていたことが原因でした… :bow )

**Comment by hayayu11** [comment]
ありがとうございます。手元の開発環境ではうまく動作した機能が、本番環境で動作してないようなのですが、production.log を確認しつつ修正することになりますか？

[個別指標](http://qi.med.kyoto-u.ac.jp/definitions/55780ee4746b323353a50000 )の各薬剤CSVダウンロード機能でエラーが発生しました。
