### ISSUE TITLE
定義書のpdf出力

### ISSUE THREAD

**Issue by hayayu11** [showwin/QIDB#48]
定義書(show.html.erb)のページを連続してpdf化出来るようにする。

http://qiita.com/awakia/items/d53ab583f214703f6afa
http://qiita.com/yu_0105/items/93b947459bcd4ee68ae0

**Comment by showwin** [comment]
> controller に ~.pdf でアクセスされた時の対応を書くのですが、違うクラスの controller を用意すべきでしょうか？

欲しいのは**定義書**のPDFなので、Definition(定義書)クラスのControllerにメソッドを追加すべきです。

**Comment by hayayu11** [comment]
素早いお返事ありがとうございます。

**Comment by hayayu11** [comment]
・pdf 出力時には、"表名"参照という形でテーブルのレコードの代わりに表示する。
--->10件だけ表示、もしくは薬価テーブルのDLボタンを作る可能性もある。
・出力用の css を作る...
