### ISSUE TITLE
DB9 で公開

### ISSUE THREAD

**Issue by hayayu11** [showwin/QIDB#53]
@showwin root で pull しないように、 hayakawa のアカウントで pull  しようとすると、 permission denied されます。前回は伊藤さんのアカウントの公開鍵を登録したのでしょうか。

**Comment by showwin** [comment]
[SSH key設定ページ](https://github.com/settings/ssh)でDB9の早川くんのアカウントで作成した公開鍵を登録すると、(早川くんのGitHubアカウントがこのレポジトリのCollaboratorsに紐付けてあるので) git pull できるようになると思います。

**Comment by hayayu11** [comment]
@showwin http://design1.chu.jp/setucocms-pjt/?p=580
このページを参考にして、公開鍵を登録したのですが、同様のエラーが出てしまいます...

**Comment by showwin** [comment]
@hayayu11 DB9の早川くんのアカウントではGitの設定をしてありますか？
[使い始める - 最初のGitの構成](http://git-scm.com/book/ja/v1/%E4%BD%BF%E3%81%84%E5%A7%8B%E3%82%81%E3%82%8B-%E6%9C%80%E5%88%9D%E3%81%AEGit%E3%81%AE%E6%A7%8B%E6%88%90) にも書かれているように、
>Gitをインストールしたときに最初にすべきことは、ユーザー名とE-mailアドレスを設定することです。全てのGitのコミットはこの情報を用いるため、これは重要で、次々とまわすコミットに永続的に焼き付けられます：
```
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
```

GitHubはここのemailの情報を使って、GitHubのアカウントと紐付けていた気がします。

**Comment by hayayu11** [comment]
@showwin  user に関する情報を設定しても、同様のエラーが出てしまいます...

**Comment by showwin** [comment]
@hayayu11
うーん、ファイル書き込み権限の問題な気がします。
僕がpullしたので、現状のファイル所有者は僕のアカウントになっているはずですが、othersもw(rite)できるような権限設定になっていますか？

**Comment by hayayu11** [comment]
@showwin 返信が遅くなりすいません。owner は伊藤さんで書き込み権限は、owner しか持っていませんでした。

**Comment by hayayu11** [comment]
セキュリティを考えると迂闊に実行出来なかったので、鍵の情報を再生成しました。再度 pull を行うと、以下のようにエラーが出たので、対処しました。

http://qiita.com/SOJO/items/74b16221580a17296226

続々と、.git 内のファイルの権限設定による問題が出てくるので、処理中です。

**Comment by hayayu11** [comment]
とりあえず仮想サーバーにおいて、公開することが出来ました。。。協力ありがとうございます。

**Comment by hayayu11** [comment]
@showwin  確認なのですが、definition model の read.csv というメソッドはエクセルファイルの一行目の文字列が、"指標群"だったらその列の値を取り込みますか？　プログラムを見る限り、"qip"という一行目の文字列があれば、「qipのパラメータ」として取り込みますか？

**Comment by showwin** [comment]
|指標群|qip|分母|jha|
|:--:|:--:|:--:|:--:|
@hayayu11 
|指標群1|qip1|分母1|jha1|
|指標群2|qip2|分母2|jha2|
|指標群3|qip3|分母3|jha3|

というように、1行目のカラムの順で2行目以降の値を取得していきます。
1行目のカラムは順不同です。

**Comment by hayayu11** [comment]
@showwin ありがとうございます。渡されたファイルには、qip の番号しかありませんでした。現在は、csv に変換すると文字化けで、(恐らく)取り込めないために、対処中です。

**Comment by hayayu11** [comment]
@showwin sakura の VPS で環境をセットアップしているのですが、エラーが出てしまいます。DB9でセットアップした時に参考にしたサイトはありますか？DB9 の passenger とバージョンの違うものを入れてしまったのですが、それ以外に考えられる要因はありますか？

 http://160.16.76.138/definitions/new

**Comment by showwin** [comment]
@hayayu11 `(rails_root)/log/produntion.log` にエラーが出てると思うので、そのエラー内容をここに貼り付けて頂けますか？
Passengerなどのミドルウェアが問題であれば、Railsがうまく動かず、今のようなRailsのエラー画面が出ることはないと思います。

**Comment by hayayu11** [comment]
@showwin その階層には、`development.log`しかなく、中身は空でした。Rails のエラー画面が出るのは、アプリケーション内のエラーかと思ったのですが、DB9やlocalでは普通に動いておりよく分かりません。何かアドバイスがあればお願いします...

**Comment by showwin** [comment]
@hayayu11 ということはProduction環境で動いていないと思うのですが、
```
$ rake assets:precompile RAILS_ENV=production
$ rake db:migrate RAILS_ENV=production
$ sudo service httpd restart
```
して、Apatcheを再起動してもダメでしょうか？

**Comment by showwin** [comment]
@hayayu11 とりあえず3000番ポートを開けて `rails s` でdevelopment環境で動かしてみるのはどうでしょう？ development環境の方がエラーメッセージがブラウザで見れるので問題が発見しやすいと思います。
`http://160.16.76.138:3000` でdevelopent環境にアクセスできるはずです。

**Comment by hayayu11** [comment]
@showwin  上の方法で公開されました。ありがとうございます。
結局、メモ帳で変換するとかエクセルで名前をつけて保存では文字コードの問題を解決出来なかったのですが、何かアドバイスを頂けますか？

**Comment by showwin** [comment]
@hayayu11
[この記事](http://qiita.com/shunsuke227ono/items/a9648f8c043ed637dc69) では万能な方法はないと言っていますね… (ちょっと目的は違いますが。)
普通に思いつくのは、インポートされたCSVの文字コードを見て、UTF-8に変換する方法だと思うのですが、それではうまくいきませんか？
なにを試してみて、なにがどううまくいかなかったのかもう少し詳細に説明して頂けると回答しやすいです。

**Comment by hayayu11** [comment]
@showwin  multi の問題のようなので、解決しました。ありがとうございます。
