### ISSUE TITLE
development 環境で詳細エラーが出ない

### ISSUE THREAD

**Issue by showwin** [showwin/QIDB#57]
#56 の続き

master ブランチを pull して、こちらの環境で試してみましたが再現できませんでした。
`config/environments/development.rb`をみても特に問題は見当たりません。
何らかの原因で、production環境で起動してしまっている可能性が考えられるので、`$ rails s -e development`と明示的に development 環境で起動してみたらどうでしょうか？

**Comment by hayayu11** [comment]
@showwin Ruby のバージョンをあげて、教えて頂いたライブラリをインストールすると、詳細も出るようになりました。
