### ISSUE TITLE
フォーム変更点(早川分)

### ISSUE THREAD

**Issue by showwin** [showwin/QIDB#7]
#5 から分岐

* 「更新日」はタイムスタンプから取得する
* 「更新日」の削除
* 「リスク調整因子の定義」の入力欄はtext_areaにする
* 「薬剤一覧出力」の欄を追加(「あり」「なし」の2択)

**Comment by hayayu11** [comment]
上記に加えて、編集者の名前とメッセージを必須にしました。

**Comment by showwin** [comment]
4011f2f のコミットで修正済み
