### ISSUE TITLE
学内からはBasic認証をはずす

### ISSUE THREAD

**Issue by hayayu11** [showwin/QIDB#70]

**Comment by showwin** [comment]
学内からだけのような、特定のアクセスだけBasic認証を外すのは無理な気がする(できたらすみません)ので、KUINSのVPNのIPからのみアクセスできるように設定して、それ以外を弾く、もしくはエラー用のページにリダイレクトする方針の方が良いと思います。

**Comment by hayayu11** [comment]
@showwin 今は、rails 内にBasic認証の記述をしていますが、調べてみると、apacheでIPアドレスを指定してBasic認証を回避する例ばかりなのでそちらでいこうと思います。どうでしょうか？

**Comment by hayayu11** [comment]
http://tm.root-n.com/server:apache:basic_authentification:allow_from_specific_ipaddr

**Comment by showwin** [comment]
@hayayu11 なるほど、Apache側で設定するんですね。それで良いと思います！　
知識不足ですみませんでした。
